language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install . --quiet
  - pip install nose --quiet
  - pip install speaklater --quiet

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.17.zip -nv
  - unzip -q google_appengine_1.9.17.zip

script:
  - export PYTHONPATH=$PYTHONPATH:google_appengine
  - nosetests

branches:
  only:
    - master
