language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install . --quiet
  - pip install nose --quiet
  - pip install speaklater --quiet

before_script:
  - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.2.zip -nv
  - unzip -q google_appengine_1.8.2.zip

script:
  - export PYTHONPATH=$PYTHONPATH:google_appengine
  - nosetests

branches:
  only:
    - master
